---
language: ruby
cache:
- bundler
- yarn
addons:
  postgresql: '10'
env:
  matrix:
  - TEST_SUITE=javascript
  - TEST_SUITE=rails
before_install: source bin/ci/before_install.sh
install: source bin/ci/install.sh
script: source bin/ci/script.sh
after_script: bin/ci/after_script
